services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=myFirstPostgres
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_DB=myFirstPostgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
volumes:
#  TODO: volume mount setup, for persisting data through multiple sessions (?)
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
